name: Auto Label PR for Auto-Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - develop

permissions:
  pull-requests: write
  contents: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'movingju' || 
      github.actor == 'suykr' 
    steps:
      - name: Add auto-merge label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "auto-merge"
